Name: Yilin Pu

Github Username: pyl32

USC ID: 2952467624

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

from sklearn.metrics import classification_report, confusion_matrix, f1_score, hamming_loss,accuracy_score
from sklearn.svm import SVC, LinearSVC
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.multiclass import OneVsRestClassifier
from sklearn.cluster import KMeans

from sklearn.metrics import silhouette_samples, silhouette_score

### 1.Multi-class and Multi-Label Classification Using Support Vector Machines
#### (a) Download the Anuran Calls (MFCCs) Data Set from: https://archive.ics.uci.edu/ml/datasets/Anuran+Calls+%28MFCCs%29. Choose 70% of the data randomly as the training set.

In [3]:
data = pd.read_csv('../data/Frogs_MFCCs.csv')

data

MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6  MFCCs_ 7  \
0          1.0  0.152936 -0.105586  0.200722  0.317201  0.260764  0.100945   
1          1.0  0.171534 -0.098975  0.268425  0.338672  0.268353  0.060835   
2          1.0  0.152317 -0.082973  0.287128  0.276014  0.189867  0.008714   
3          1.0  0.224392  0.118985  0.329432  0.372088  0.361005  0.015501   
4          1.0  0.087817 -0.068345  0.306967  0.330923  0.249144  0.006884   
...        ...       ...       ...       ...       ...       ...       ...   
7190       1.0 -0.554504 -0.337717  0.035533  0.034511  0.443451  0.093889   
7191       1.0 -0.517273 -0.370574  0.030673  0.068097  0.402890  0.096628   
7192       1.0 -0.582557 -0.343237  0.029468  0.064179  0.385596  0.114905   
7193       1.0 -0.519497 -0.307553 -0.004922  0.072865  0.377131  0.086866   
7194       1.0 -0.508833 -0.324106  0.062068  0.078211  0.397188  0.094596   

      MFCCs_ 8  MFCCs_ 9  MFCCs_10  ...  MFCCs_17  MFCCs_18  MFCCs_19  \
0    -0.150063 -0.171128  0.124676  ... -0.108351 -0.077623 -0.009568   
1    -0.222475 -0.207693  0.170883  ... -0.090974 -0.056510 -0.035303   
2    -0.242234 -0.219153  0.232538  ... -0.050691 -0.023590 -0.066722   
3    -0.194347 -0.098181  0.270375  ... -0.136009 -0.177037 -0.130498   
4    -0.265423 -0.172700  0.266434  ... -0.048885 -0.053074 -0.088550   
...        ...       ...       ...  ...       ...       ...       ...   
7190 -0.100753  0.037087  0.081075  ...  0.069430  0.071001  0.021591   
7191 -0.116460  0.063727  0.089034  ...  0.061127  0.068978  0.017745   
7192 -0.103317  0.070370  0.081317  ...  0.082474  0.077771 -0.009688   
7193 -0.115799  0.056979  0.089316  ...  0.051796  0.069073  0.017963   
7194 -0.117672  0.058874  0.076180  ...  0.061455  0.072983 -0.003980   

      MFCCs_20  MFCCs_21  MFCCs_22           Family      Genus  \
0     0.057684  0.118680  0.014038  Leptodactylidae  Adenomera   
1     0.020140  0.082263  0.029056  Leptodactylidae  Adenomera   
2    -0.025083  0.099108  0.077162  Leptodactylidae  Adenomera   
3    -0.054766 -0.018691  0.023954  Leptodactylidae  Adenomera   
4    -0.031346  0.108610  0.079244  Leptodactylidae  Adenomera   
...        ...       ...       ...              ...        ...   
7190  0.052449 -0.021860 -0.079860          Hylidae     Scinax   
7191  0.046461 -0.015418 -0.101892          Hylidae     Scinax   
7192  0.027834 -0.000531 -0.080425          Hylidae     Scinax   
7193  0.041803 -0.027911 -0.096895          Hylidae     Scinax   
7194  0.031560 -0.029355 -0.087910          Hylidae     Scinax   

             Species  RecordID  
0     AdenomeraAndre         1  
1     AdenomeraAndre         1  
2     AdenomeraAndre         1  
3     AdenomeraAndre         1  
4     AdenomeraAndre         1  
...              ...       ...  
7190     ScinaxRuber        60  
7191     ScinaxRuber        60  
7192     ScinaxRuber        60  
7193     ScinaxRuber        60  
7194     ScinaxRuber        60  

[7195 rows x 26 columns]

In [11]:
data.drop(columns='RecordID',inplace= True)

In [12]:
data_x = data.iloc[:,:-4]
data_y = data.iloc[:,-3:]

train_x,  test_x, train_y, test_y = train_test_split(data_x, data_y, test_size = 0.3, random_state = 50)
print(train_y['Family'].value_counts(), train_y['Species'].value_counts(), train_y['Genus'].value_counts())

frog_data = data
frog_data['Family'], fam_labels = pd.factorize(frog_data['Family'])
frog_data['Species'], species_labels = pd.factorize(frog_data['Species'])
frog_data['Genus'], gen_labels = pd.factorize(frog_data['Genus'])
print(frog_data)


frog_datax = frog_data.iloc[:,:-4]
frog_datay = frog_data.iloc[:,-3:]

trainx,  testx, trainy,testy = train_test_split(frog_datax, frog_datay, test_size = 0.3, random_state = 50)

print(frog_datax, frog_datay)

0    3119
2    1486
1     386
3      45
Name: Family, dtype: int64 2    2443
5     778
0     478
1     386
4     316
3     216
6     198
9      97
7      79
8      45
Name: Species, dtype: int64 0    2921
3    1094
1     386
2     216
4     198
7      97
5      79
6      45
Name: Genus, dtype: int64
      MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6  MFCCs_ 7  \
0          1.0  0.152936 -0.105586  0.200722  0.317201  0.260764  0.100945   
1          1.0  0.171534 -0.098975  0.268425  0.338672  0.268353  0.060835   
2          1.0  0.152317 -0.082973  0.287128  0.276014  0.189867  0.008714   
3          1.0  0.224392  0.118985  0.329432  0.372088  0.361005  0.015501   
4          1.0  0.087817 -0.068345  0.306967  0.330923  0.249144  0.006884   
...        ...       ...       ...       ...       ...       ...       ...   
7190       1.0 -0.554504 -0.337717  0.035533  0.034511  0.443451  0.093889   
7191       1.0 -0.517273 -0.370574  0.030673  0.068097  0.402890  0.096628 

#### (b) Each instance has three labels: Families, Genus, and Species. Each of the labels has multiple classes. We wish to solve a multi-class and multi-label problem. One of the most important approaches to multi-label classification is to train a classifier for each label (binary relevance). We first try this approach:

##### i.Research exact match and hamming score/ loss methods for evaluating multi-label classification and use them in evaluating the classifiers in this problem.


Exact match is a harsh approach which checks if all the labels are classified correctly.

Hamming loss is the fraction of wrong labels to the total number of labels

##### ii.Train a SVM for each of the labels, using Gaussian kernels and one versus all classifiers. Determine the weight of the SVM penalty and the width of the Gaussian Kernel using 10 fold cross validation.1You are welcome to try to solve the problem with both standardized 2 and raw attributes and report the results.

In [13]:
mod_family = SVC(C=0.01,kernel='rbf',gamma=0.1,decision_function_shape='ovr')
mod_family.fit(train_x, train_y['Family'])
pred_family = mod_family.predict(train_x)
print(accuracy_score(train_y['Family'], pred_family))

mod_family = SVC(C=0.1,kernel='rbf',gamma=0.2,decision_function_shape='ovr')
mod_family.fit(train_x, train_y['Family'])
pred_family = mod_family.predict(train_x)
print(accuracy_score(train_y['Family'], pred_family))

mod_family = SVC(C=100,kernel='rbf',gamma=2,decision_function_shape='ovr')
mod_family.fit(train_x, train_y['Family'])
pred_family = mod_family.predict(train_x)
print(accuracy_score(train_y['Family'], pred_family))

mod_family = SVC(C=1000,kernel='rbf',gamma=0.1,decision_function_shape='ovr')
mod_family.fit(train_x, train_y['Family'])
pred_family = mod_family.predict(train_x)
print(accuracy_score(train_y['Family'], pred_family))

mod_family = SVC(C=1000,kernel='rbf',gamma=2,decision_function_shape='ovr')
mod_family.fit(train_x, train_y['Family'])
pred_family = mod_family.predict(train_x)
print(accuracy_score(train_y['Family'], pred_family))

0.6199364575059572
0.9348689436060366
1.0
0.9974185861795075
1.0


In [34]:
np.logspace(start = -2,stop = 3, num = 6)

tuned_param = [{ 'gamma': np.arange(.2,2.1,.1), 'C': np.logspace(start = -2,stop = 3, num = 6)}]

def chooseParam( train_x, train_y, test_x, test_y, model = SVC(kernel='rbf'),tuned_params=tuned_param):
    model = GridSearchCV(estimator=model, param_grid = tuned_param, scoring = 'f1_weighted', n_jobs = -1,\
                       cv = StratifiedKFold(10, random_state = 100, shuffle=True) )
    
    model.fit(train_x, train_y)
    
    print("Grid scores are: ")
    
    
    means = model.cv_results_['mean_test_score']
    stds = model.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, model.cv_results_['params']):
        print("%0.2f (+/-%0.02f) for %r"
              % (mean, std * 2, params))
    print("The best parameters are: ",model.best_params_)
    print("The best score for the SVM is: ",model.best_score_)

    
    test_pred = model.predict(test_x)
    print("The classification report: ",classification_report(test_y, test_pred))
    return model

In [16]:
gaussian_family = chooseParam(trainx, trainy['Family'], testx, testy['Family'])

gaussian_genus = chooseParam(trainx, trainy['Genus'], testx, testy['Genus'])

gaussian_species = chooseParam(trainx, trainy['Species'], testx, testy['Species'])


Grid scores are: 
0.62 (+/-0.02) for {'C': 0.01, 'gamma': 0.2}
0.78 (+/-0.01) for {'C': 0.01, 'gamma': 0.30000000000000004}
0.80 (+/-0.02) for {'C': 0.01, 'gamma': 0.4000000000000001}
0.81 (+/-0.02) for {'C': 0.01, 'gamma': 0.5000000000000001}
0.81 (+/-0.02) for {'C': 0.01, 'gamma': 0.6000000000000001}
0.81 (+/-0.02) for {'C': 0.01, 'gamma': 0.7000000000000002}
0.82 (+/-0.02) for {'C': 0.01, 'gamma': 0.8000000000000003}
0.82 (+/-0.02) for {'C': 0.01, 'gamma': 0.9000000000000001}
0.82 (+/-0.02) for {'C': 0.01, 'gamma': 1.0000000000000002}
0.83 (+/-0.02) for {'C': 0.01, 'gamma': 1.1000000000000003}
0.83 (+/-0.02) for {'C': 0.01, 'gamma': 1.2000000000000004}
0.83 (+/-0.02) for {'C': 0.01, 'gamma': 1.3000000000000003}
0.83 (+/-0.02) for {'C': 0.01, 'gamma': 1.4000000000000004}
0.83 (+/-0.02) for {'C': 0.01, 'gamma': 1.5000000000000004}
0.83 (+/-0.02) for {'C': 0.01, 'gamma': 1.6000000000000003}
0.83 (+/-0.02) for {'C': 0.01, 'gamma': 1.7000000000000004}
0.83 (+/-0.02) for {'C': 0.01, 'gamm

Grid scores are: 
0.46 (+/-0.02) for {'C': 0.01, 'gamma': 0.2}
0.58 (+/-0.01) for {'C': 0.01, 'gamma': 0.30000000000000004}
0.65 (+/-0.01) for {'C': 0.01, 'gamma': 0.4000000000000001}
0.72 (+/-0.02) for {'C': 0.01, 'gamma': 0.5000000000000001}
0.75 (+/-0.03) for {'C': 0.01, 'gamma': 0.6000000000000001}
0.77 (+/-0.02) for {'C': 0.01, 'gamma': 0.7000000000000002}
0.78 (+/-0.02) for {'C': 0.01, 'gamma': 0.8000000000000003}
0.78 (+/-0.02) for {'C': 0.01, 'gamma': 0.9000000000000001}
0.79 (+/-0.02) for {'C': 0.01, 'gamma': 1.0000000000000002}
0.79 (+/-0.02) for {'C': 0.01, 'gamma': 1.1000000000000003}
0.79 (+/-0.02) for {'C': 0.01, 'gamma': 1.2000000000000004}
0.79 (+/-0.02) for {'C': 0.01, 'gamma': 1.3000000000000003}
0.79 (+/-0.02) for {'C': 0.01, 'gamma': 1.4000000000000004}
0.79 (+/-0.02) for {'C': 0.01, 'gamma': 1.5000000000000004}
0.79 (+/-0.02) for {'C': 0.01, 'gamma': 1.6000000000000003}
0.79 (+/-0.02) for {'C': 0.01, 'gamma': 1.7000000000000004}
0.79 (+/-0.02) for {'C': 0.01, 'gamm

In [24]:
def AllDisplay(model, train_x, train_y, test_x, test_y, label ):

    ova_svm = OneVsRestClassifier(SVC(kernel='rbf', C = model.best_params_['C'], gamma = model.best_params_['gamma'], probability=True))
    ova_svm_fit =  ova_svm.fit(train_x, train_y)
    

    pred_y_train = ova_svm_fit.predict(train_x)
    print("The confusion matrix of the training data ",label," is \n",confusion_matrix(train_y, pred_y_train))
    print("F1-score of the training data %s is \n%0.3f "  %(label, f1_score(train_y, pred_y_train, average='weighted'))) 
    

    pred_y_test = ova_svm_fit.predict(test_x)
    print("The confusion matrix of the testing data ",label," is \n",confusion_matrix(test_y, pred_y_test))
    print("F1-score of the testing data %s is \n%0.3f "  %(label , f1_score(test_y, pred_y_test, average='weighted'))) 
    

    print("The hamming loss of the testing data ",label," is \n",hamming_loss(test_y, pred_y_test))
    print("The exact match of the testing data ",label," is \n",\
          accuracy_score(test_y, pred_y_test))
    return test_y, pred_y_test

In [25]:
test_y_fam, pred_y_fam = AllDisplay(gaussian_family, trainx, trainy['Family'], testx, testy['Family'],'Family')

test_y_gen, pred_y_gen = AllDisplay(gaussian_genus, trainx, trainy['Genus'], testx, testy['Genus'],'Genus')

test_y_spec, pred_y_spec = AllDisplay(gaussian_species, trainx, trainy['Species'], testx, testy['Species'],'Species')

The confusion matrix of the training data  Family  is 
 [[3119    0    0    0]
 [   0  386    0    0]
 [   0    0 1486    0]
 [   0    0    0   45]]
F1-score of the training data Family is 
1.000 
The confusion matrix of the testing data  Family  is 
 [[1289    1   11    0]
 [   0  156    0    0]
 [   3    0  673    3]
 [   0    0    1   22]]
F1-score of the testing data Family is 
0.991 
The hamming loss of the testing data  Family  is 
 0.008800370541917554
The exact match of the testing data  Family  is 
 0.9911996294580825
The confusion matrix of the training data  Genus  is 
 [[2920    0    1    0    0    0    0    0]
 [   0  386    0    0    0    0    0    0]
 [   3    0  213    0    0    0    0    0]
 [   0    0    0 1094    0    0    0    0]
 [   0    0    0    0  198    0    0    0]
 [   0    0    0    2    0   77    0    0]
 [   0    0    0    0    0    0   45    0]
 [   0    0    0    0    0    0    0   97]]
F1-score of the training data Genus is 
0.999 
The confusion matrix

##### iii.Repeat 1(b)ii with L1-penalized SVMs.3Remember to standardize the attributes. Determine the weight of the SVM penalty using 10 fold cross validation.


In [26]:
def stdscaler(input):
    scaler = StandardScaler()
    val_x = scaler.fit_transform(input)
    val_x = pd.DataFrame(val_x)
    val_x.columns = input.columns
    return val_x

std_trainx  = stdscaler(trainx)
std_testx = stdscaler(testx)

In [37]:
fam_l1_std = chooseParam(std_trainx, trainy['Family'], std_testx, testy['Family'])

fam_l1_raw = chooseParam(trainx, trainy['Family'], testx, testy['Family'])

Grid scores are: 
0.74 (+/-0.02) for {'C': 0.01, 'gamma': 0.2}
0.69 (+/-0.03) for {'C': 0.01, 'gamma': 0.30000000000000004}
0.68 (+/-0.03) for {'C': 0.01, 'gamma': 0.4000000000000001}
0.67 (+/-0.04) for {'C': 0.01, 'gamma': 0.5000000000000001}
0.65 (+/-0.04) for {'C': 0.01, 'gamma': 0.6000000000000001}
0.63 (+/-0.04) for {'C': 0.01, 'gamma': 0.7000000000000002}
0.59 (+/-0.02) for {'C': 0.01, 'gamma': 0.8000000000000003}
0.55 (+/-0.03) for {'C': 0.01, 'gamma': 0.9000000000000001}
0.52 (+/-0.04) for {'C': 0.01, 'gamma': 1.0000000000000002}
0.50 (+/-0.02) for {'C': 0.01, 'gamma': 1.1000000000000003}
0.48 (+/-0.01) for {'C': 0.01, 'gamma': 1.2000000000000004}
0.47 (+/-0.00) for {'C': 0.01, 'gamma': 1.3000000000000003}
0.47 (+/-0.00) for {'C': 0.01, 'gamma': 1.4000000000000004}
0.47 (+/-0.00) for {'C': 0.01, 'gamma': 1.5000000000000004}
0.47 (+/-0.00) for {'C': 0.01, 'gamma': 1.6000000000000003}
0.47 (+/-0.00) for {'C': 0.01, 'gamma': 1.7000000000000004}
0.47 (+/-0.00) for {'C': 0.01, 'gamm

In [ ]:
gen_l1_std = chooseParam(std_trainx, trainy['Genus'], std_testx, testy['Genus'])

gen_l1_raw = chooseParam(trainx, trainy['Genus'], testx, testy['Genus'])

In [ ]:
spec_l1_std = chooseParam(std_trainx, trainy['Species'], std_testx, testy['Species'])

spec_l1_raw = chooseParam(trainx, trainy['Species'], testx, testy['Species'])

In [39]:
def L1Display(model, train_x, train_y, test_x, test_y, label):

    l1_ova =  LinearSVC(penalty='l1',C=model.best_params_['C'], multi_class='ovr',dual=False)
    l1_fit =  l1_ova.fit(train_x, train_y)

    pred_y_train = l1_fit.predict(train_x)
    print("The confusion matrix of the training data ",label," is \n",confusion_matrix(train_y, pred_y_train))
    print("F1-score of the training data %s is \n%0.2f "  %(label, f1_score(train_y, pred_y_train, average='weighted'))) 
    
    pred_y_test = l1_fit.predict(test_x)
    print("The confusion matrix of the testing data ",label," is \n",confusion_matrix(test_y, pred_y_test))
    print("F1-score of the testing data %s is \n%0.2f "  %(label , f1_score(test_y, pred_y_test, average='weighted'))) 
    
    print("The hamming loss of the testing data ",label," is \n",hamming_loss(test_y, pred_y_test))
    print("The exact match of the testing data ",label," is \n",\
          accuracy_score(test_y, pred_y_test))
    return test_y, pred_y_test

In [40]:
test_y_fam_l1_std, pred_y_fam_l1_std = L1Display(fam_l1_std, std_trainx, trainy['Family'], std_testx, testy['Family'],'Family')

test_y_fam_l1, pred_y_fam_l1 = L1Display(fam_l1_raw, trainx, trainy['Family'], testx, testy['Family'],'Family')

/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


The confusion matrix of the training data  Family  is 
 [[3038   22   59    0]
 [   8  350   28    0]
 [ 123   13 1348    2]
 [   6    0   39    0]]
F1-score of the training data Family is 
0.94 
The confusion matrix of the testing data  Family  is 
 [[1265   10   26    0]
 [  10  138    8    0]
 [  55   12  611    1]
 [   1    0   22    0]]
F1-score of the testing data Family is 
0.93 
The hamming loss of the testing data  Family  is 
 0.06716072255673923
The exact match of the testing data  Family  is 
 0.9328392774432608
The confusion matrix of the training data  Family  is 
 [[3037   23   59    0]
 [   8  348   30    0]
 [ 124   14 1347    1]
 [   6    0   39    0]]
F1-score of the training data Family is 
0.94 
The confusion matrix of the testing data  Family  is 
 [[1264   11   26    0]
 [  10  139    7    0]
 [  51   13  614    1]
 [   1    0   22    0]]
F1-score of the testing data Family is 
0.93 
The hamming loss of the testing data  Family  is 
 0.06577119036591014
The exact

/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [ ]:
test_y_gen_l1_std, pred_y_gen_l1_std = L1Display(gen_l1_std, std_trainx, trainy['Genus'], std_testx, testy['Genus'],'Genus')

test_y_gen_l1, pred_y_gen_l1 = L1Display(gen_l1_raw, trainx, trainy['Genus'], testx, testy['Genus'],'Genus')

In [ ]:
test_y_spec_l1_std, pred_y_spec_l1_std = L1Display(spec_l1_std, std_trainx, trainy['Species'], std_testx, testy['Species'],'Species')

test_y_spec_l1, pred_y_spec_l1 = L1Display(spec_l1_raw, trainx, trainy['Species'], testx, testy['Species'],'Species')

##### iv.Repeat 1(b)iii by using SMOTE or any other method you know to remedy class imbalance. Report your conclusions about the classifiers you trained.

In [45]:
def smoteData( Xtrain, Ytrain):
    smote = SMOTE(random_state = 50)
    Xsmote, Ysmote = smote.fit_resample(Xtrain, Ytrain)
    Xsmote_df = pd.DataFrame(data = Xsmote, columns=Xtrain.columns)
    Ysmote_df = pd.DataFrame(data = Ysmote)
    return Xsmote_df, Ysmote_df

In [65]:
X_fam_smote_std, Y_fam_smote_std = smoteData(std_trainx, trainy['Family'])
X_fam_smote, Y_fam_smote = smoteData(trainx, trainy['Family'])


fam_smote_std = chooseParam(X_fam_smote_std, Y_fam_smote_std, std_testx, testy['Family'])
fam_smote = chooseParam(X_fam_smote, Y_fam_smote, testx, testy['Family'])

test_y_fam_sm, pred_y_fam_sm = L1Display(fam_smote, X_fam_smote, Y_fam_smote, testx, testy['Family'],'Family')

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


Grid scores are: 
0.94 (+/-0.01) for {'C': 0.01, 'gamma': 0.2}
0.94 (+/-0.01) for {'C': 0.01, 'gamma': 0.30000000000000004}
0.90 (+/-0.02) for {'C': 0.01, 'gamma': 0.4000000000000001}
0.84 (+/-0.02) for {'C': 0.01, 'gamma': 0.5000000000000001}
0.80 (+/-0.02) for {'C': 0.01, 'gamma': 0.6000000000000001}
0.77 (+/-0.01) for {'C': 0.01, 'gamma': 0.7000000000000002}
0.75 (+/-0.02) for {'C': 0.01, 'gamma': 0.8000000000000003}
0.73 (+/-0.02) for {'C': 0.01, 'gamma': 0.9000000000000001}
0.71 (+/-0.02) for {'C': 0.01, 'gamma': 1.0000000000000002}
0.69 (+/-0.02) for {'C': 0.01, 'gamma': 1.1000000000000003}
0.67 (+/-0.02) for {'C': 0.01, 'gamma': 1.2000000000000004}
0.66 (+/-0.04) for {'C': 0.01, 'gamma': 1.3000000000000003}
0.64 (+/-0.07) for {'C': 0.01, 'gamma': 1.4000000000000004}
0.62 (+/-0.10) for {'C': 0.01, 'gamma': 1.5000000000000004}
0.58 (+/-0.08) for {'C': 0.01, 'gamma': 1.6000000000000003}
0.56 (+/-0.10) for {'C': 0.01, 'gamma': 1.7000000000000004}
0.55 (+/-0.12) for {'C': 0.01, 'gamm

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


Grid scores are: 
0.82 (+/-0.02) for {'C': 0.01, 'gamma': 0.2}
0.88 (+/-0.01) for {'C': 0.01, 'gamma': 0.30000000000000004}
0.89 (+/-0.01) for {'C': 0.01, 'gamma': 0.4000000000000001}
0.89 (+/-0.01) for {'C': 0.01, 'gamma': 0.5000000000000001}
0.89 (+/-0.01) for {'C': 0.01, 'gamma': 0.6000000000000001}
0.90 (+/-0.01) for {'C': 0.01, 'gamma': 0.7000000000000002}
0.90 (+/-0.01) for {'C': 0.01, 'gamma': 0.8000000000000003}
0.91 (+/-0.01) for {'C': 0.01, 'gamma': 0.9000000000000001}
0.92 (+/-0.01) for {'C': 0.01, 'gamma': 1.0000000000000002}
0.92 (+/-0.01) for {'C': 0.01, 'gamma': 1.1000000000000003}
0.92 (+/-0.01) for {'C': 0.01, 'gamma': 1.2000000000000004}
0.93 (+/-0.01) for {'C': 0.01, 'gamma': 1.3000000000000003}
0.93 (+/-0.01) for {'C': 0.01, 'gamma': 1.4000000000000004}
0.93 (+/-0.01) for {'C': 0.01, 'gamma': 1.5000000000000004}
0.93 (+/-0.01) for {'C': 0.01, 'gamma': 1.6000000000000003}
0.93 (+/-0.01) for {'C': 0.01, 'gamma': 1.7000000000000004}
0.93 (+/-0.01) for {'C': 0.01, 'gamm

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


The confusion matrix of the training data  Family  is 
 [[2918   59   94   48]
 [  13 3100    6    0]
 [ 159  122 2751   87]
 [   0    0   24 3095]]
F1-score of the training data Family is 
0.95 
The confusion matrix of the testing data  Family  is 
 [[1211   18   44   28]
 [   4  150    1    1]
 [  36   33  587   23]
 [   1    0    1   21]]
F1-score of the testing data Family is 
0.92 


/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


TypeError: 'numpy.float64' object is not callable

In [ ]:
X_gen_smote_std, Y_gen_smote_std = smoteData(std_trainx, trainy['Genus'])
X_gen_smote, Y_gen_smote = smoteData(trainx, trainy['Genus'])

X_spec_smote_std, Y_spec_smotes = smoteData(std_trainx, trainy['Species'])
X_spec_smote, Y_spec_smote = smoteData(trainx, trainy['Species'])


gen_l1_smote_std = chooseParam(X_gen_smote_std, Y_gen_smote_std , std_testx, testy['Genus'])
gen_l1_smote = chooseParam(X_gen_smote, Y_gen_smote , testx, testy['Genus'])

spe_l1_smote_std = chooseParam(X_spec_smote_std, Y_spec_smotes, std_testx, testy['Species'])
spe_l1_smote = chooseParam(X_spec_smote, Y_spec_smote, testx, testy['Species'])

In [ ]:
test_y_gen_sm, pred_y_gen_sm = L1Display(gen_l1_smote, X_gen_smote, Y_gen_smote, testx, testy['Genus'],'Genus')

test_y_spe_sm, pred_y_spe_sm = L1Display(spe_l1_smote, X_spec_smote, Y_spec_smote, testx, testy['Species'],'Species')

### 2. K-Means Clustering on a Multi-Class and Multi-Label Data Set
#### Monte-Carlo Simulation: Perform the following procedures 50 times, and report the average and standard deviation of the 50 Hamming Distances that you calculate.

#### (a) Use k-means clustering on the whole Anuran Calls (MFCCs) Data Set (do not split the data into train and test, as we are not performing supervised learning in this exercise). Choose k∈ {1,2, . . . ,50} automatically based on one of the methods provided in the slides (CH or Gap Statistics or scree plots or Silhouettes) or any other method you know.

In [48]:
def Silhoutte(kmax, Xtrain, rand= 50 ):
    best_K = 2
    best_score = 0
    sil_score = np.array([])
    k_val = np.array([])
    for k in range(2, kmax+1):
        k_val = np.append(k_val, k)
        kmeans = KMeans(n_clusters = k, random_state = rand)
        labels = kmeans.fit_predict(Xtrain)
        cur_score = silhouette_score(Xtrain, labels, metric = 'euclidean')
        print("For ", k," clusters, the average silhouette score is: ", cur_score)
        sil_score  = np.append(sil_score, cur_score)
    ind = np.argmax(sil_score)
    best_K = k_val[ind]
    
    print("The best K is: {}".format(best_K))
    return best_K, sil_score

In [49]:
best_k, sil_score = Silhoutte(50, data_x)

For  2  clusters, the average silhouette score is:  0.3412583721362144
For  3  clusters, the average silhouette score is:  0.36357542165726875
For  4  clusters, the average silhouette score is:  0.37567709025469104
For  5  clusters, the average silhouette score is:  0.3684660773649927
For  6  clusters, the average silhouette score is:  0.23907293117080378
For  7  clusters, the average silhouette score is:  0.261929079688483
For  8  clusters, the average silhouette score is:  0.28125028548307623
For  9  clusters, the average silhouette score is:  0.2781660668707387
For  10  clusters, the average silhouette score is:  0.2659119754545092
For  11  clusters, the average silhouette score is:  0.2742402210995423
For  12  clusters, the average silhouette score is:  0.2774461871965752
For  13  clusters, the average silhouette score is:  0.2603156109102131
For  14  clusters, the average silhouette score is:  0.2652471637794952
For  15  clusters, the average silhouette score is:  0.27325898077345

#### (b)In each cluster, determine which family is the majority by reading the true labels. Repeat for genus and species.

In [50]:
def themajority(label, all_labels):
    clusters = list(set(all_labels))
    clusters.sort()
    majority = np.array([])

    for cur_clus in clusters:
        
        index, = np.where(all_labels == cur_clus)
        cluster_item = label[index]
        majority = np.append(majority, cluster_item.value_counts().idxmax())
    majority = pd.Series(majority)
    return majority 

In [51]:
km = KMeans(n_clusters = best_k.astype(int), random_state = 0)
cluster_lab = km.fit_predict(data_x)

majority_fam = themajority( data_y['Family'], cluster_lab)
print("Majority in Family label is \n",majority_fam)

majority_gen = themajority( data_y['Genus'], cluster_lab)
print("Majority in Genus label is \n",majority_gen)

majority_spe = themajority( data_y['Species'], cluster_lab)
print("Majority in Species label is \n",majority_spe)

Majority in Family label is 
 0    1.0
1    0.0
2    2.0
3    2.0
dtype: float64
Majority in Genus label is 
 0    1.0
1    0.0
2    3.0
3    3.0
dtype: float64
Majority in Species label is 
 0    1.0
1    2.0
2    5.0
3    4.0
dtype: float64


#### (c) Now for each cluster you have a majority label triplet (family, genus, species). Calculate the average Hamming distance, Hamming score, and Hamming loss between the true labels and the labels assigned by clusters.

In [52]:
def getPred( majority, all_labels):
    clusters = list(set(all_labels))
    
    pred_lab = np.empty(len(all_labels), dtype="object")

    for cur_clus in clusters:
        index, = np.where(all_labels == cur_clus)
        pred_lab[index] = majority[cur_clus]
    return pred_lab 

In [53]:
label_fam = getPred( majority_fam, cluster_lab)
print(label_fam)
label_gen = getPred(majority_gen, cluster_lab)
print(label_gen)
label_spe = getPred(majority_spe, cluster_lab)
print(label_spe)

[1.0 1.0 1.0 ... 1.0 1.0 1.0]
[1.0 1.0 1.0 ... 1.0 1.0 1.0]
[1.0 1.0 1.0 ... 1.0 1.0 1.0]


In [58]:

def hamm_loss(true_arr, pred_arr, avg_dist = False):
    sums = np.sum(np.not_equal(true_arr[2],pred_arr[2])) + \
    np.sum(np.not_equal(true_arr[1],pred_arr[1])) + np.sum(np.not_equal(true_arr[0],pred_arr[0]))
    denom = true_arr.shape[0] * true_arr.shape[1]
    ham_loss = sums/denom
    
    if avg_dist == True:
        avg_ham_dist = sums/true_arr.shape[1]
        return avg_ham_dist, ham_loss
    
    return ham_loss

In [59]:
true_arr_k = np.vstack([data_y['Family'],data_y['Genus'],data_y['Species']])
pred_arr_k =  np.vstack([label_fam, label_gen, label_spe] )

avg_dist,hamming_loss = hamm_loss(true_arr_k, pred_arr_k, True)
print("The avg hamming distance: ",avg_dist," and hamming loss is ",hamming_loss)

print("The avg Hamming score is",(1 - np.mean(hamming_loss)))

The avg hamming distance:  0.6653231410701876  and hamming loss is  0.22177438035672922
The avg Hamming score is 0.7782256196432707


In [60]:
def monteCarlo(n, Xtrain, ytrain  ):
    true_arr_mc = np.vstack([ytrain['Family'], ytrain['Genus'], ytrain['Species']])
    ham_all = np.array([])
    ham_dist = np.array([])
    for i in range(n):
        
        best_k, sil_score = Silhoutte(n, Xtrain, i) 

        km = KMeans(n_clusters= best_k.astype(int), random_state = 50)
        cluster_lab = km.fit_predict(Xtrain)

        majority_fam = themajority( ytrain['Family'], cluster_lab)

        majority_gen = themajority( ytrain['Genus'], cluster_lab)

        majority_spe = themajority( ytrain['Species'], cluster_lab)
        
        label_fam = getPred( majority_fam, cluster_lab)
        label_gen = getPred(majority_gen, cluster_lab)
        label_spe = getPred(majority_spe, cluster_lab)
        pred_arr_k =  np.vstack([label_fam, label_gen, label_spe] )

        avg_ham_dist, ham_lossmc = hamm_loss(true_arr_k, pred_arr_k, True)
        print("For iteration[", i, "] The hamming loss is:", best_k, " is", ham_lossmc)
        print("For iteration[", i, "] The hamming dist is:", best_k, " is", avg_ham_dist)

        ham_all = np.append(ham_all, ham_lossmc) 
        ham_dist = np.append(ham_dist, avg_ham_dist) 
    return ham_dist, ham_all

In [62]:
all_dist, all_hamming = monteCarlo(50 ,data_x, data_y)

For  2  clusters, the average silhouette score is:  0.3412583721362144
For  3  clusters, the average silhouette score is:  0.36357542165726875
For  4  clusters, the average silhouette score is:  0.3756069243766642
For  5  clusters, the average silhouette score is:  0.36843812657852376
For  6  clusters, the average silhouette score is:  0.264968956504193
For  7  clusters, the average silhouette score is:  0.2698239832783356
For  8  clusters, the average silhouette score is:  0.28126203986095577
For  9  clusters, the average silhouette score is:  0.2668046683011723
For  10  clusters, the average silhouette score is:  0.26619228471812145
For  11  clusters, the average silhouette score is:  0.28062988733873206
For  12  clusters, the average silhouette score is:  0.2736717151342834
For  13  clusters, the average silhouette score is:  0.2796000221256626
For  14  clusters, the average silhouette score is:  0.2831488874652245
For  15  clusters, the average silhouette score is:  0.2727975404901

For  14  clusters, the average silhouette score is:  0.2670266739624214
For  15  clusters, the average silhouette score is:  0.2638811235468414
For  16  clusters, the average silhouette score is:  0.27773342275681906
For  17  clusters, the average silhouette score is:  0.28175191372578573
For  18  clusters, the average silhouette score is:  0.2666148384585363
For  19  clusters, the average silhouette score is:  0.27327633246708677
For  20  clusters, the average silhouette score is:  0.2774462175384564
For  21  clusters, the average silhouette score is:  0.26739211975067234
For  22  clusters, the average silhouette score is:  0.27696291197908934
For  23  clusters, the average silhouette score is:  0.27493836304795316
For  24  clusters, the average silhouette score is:  0.2643240736725294
For  25  clusters, the average silhouette score is:  0.2648531832984025
For  26  clusters, the average silhouette score is:  0.28126354813059773
For  27  clusters, the average silhouette score is:  0.26

For  26  clusters, the average silhouette score is:  0.2691228480371075
For  27  clusters, the average silhouette score is:  0.2712872164327034
For  28  clusters, the average silhouette score is:  0.2678418085087362
For  29  clusters, the average silhouette score is:  0.2678412445155946
For  30  clusters, the average silhouette score is:  0.2662051513205957
For  31  clusters, the average silhouette score is:  0.26484397453637215
For  32  clusters, the average silhouette score is:  0.2625276779109241
For  33  clusters, the average silhouette score is:  0.2628893436236294
For  34  clusters, the average silhouette score is:  0.262018470067843
For  35  clusters, the average silhouette score is:  0.26347156987964865
For  36  clusters, the average silhouette score is:  0.26156705267202973
For  37  clusters, the average silhouette score is:  0.2623042239377699
For  38  clusters, the average silhouette score is:  0.2630743613483517
For  39  clusters, the average silhouette score is:  0.2678093

For  38  clusters, the average silhouette score is:  0.25528051029677384
For  39  clusters, the average silhouette score is:  0.25601529550001406
For  40  clusters, the average silhouette score is:  0.24018987230777233
For  41  clusters, the average silhouette score is:  0.24093868555445427
For  42  clusters, the average silhouette score is:  0.21670903654940504
For  43  clusters, the average silhouette score is:  0.2482578905493178
For  44  clusters, the average silhouette score is:  0.2215559091131063
For  45  clusters, the average silhouette score is:  0.24381006111302153
For  46  clusters, the average silhouette score is:  0.24625462197008802
For  47  clusters, the average silhouette score is:  0.24670033437493802
For  48  clusters, the average silhouette score is:  0.2074963054250576
For  49  clusters, the average silhouette score is:  0.20468884331101422
For  50  clusters, the average silhouette score is:  0.21804786911858756
The best K is: 4.0
For iteration[ 6 ] The hamming loss

For  50  clusters, the average silhouette score is:  0.22981174093112539
The best K is: 4.0
For iteration[ 8 ] The hamming loss is: 4.0  is 0.22233032198285846
For iteration[ 8 ] The hamming dist is: 4.0  is 0.6669909659485754
For  2  clusters, the average silhouette score is:  0.3412583721362144
For  3  clusters, the average silhouette score is:  0.36357542165726875
For  4  clusters, the average silhouette score is:  0.38145951962598956
For  5  clusters, the average silhouette score is:  0.3678539763410576
For  6  clusters, the average silhouette score is:  0.264968956504193
For  7  clusters, the average silhouette score is:  0.26201152983848386
For  8  clusters, the average silhouette score is:  0.26577545655282053
For  9  clusters, the average silhouette score is:  0.26669908351745136
For  10  clusters, the average silhouette score is:  0.26666486402674927
For  11  clusters, the average silhouette score is:  0.2746528660969234
For  12  clusters, the average silhouette score is:  0.2

For  10  clusters, the average silhouette score is:  0.2655044477260958
For  11  clusters, the average silhouette score is:  0.2643114947088811
For  12  clusters, the average silhouette score is:  0.27452333133218776
For  13  clusters, the average silhouette score is:  0.2607493048620513
For  14  clusters, the average silhouette score is:  0.2622888939585479
For  15  clusters, the average silhouette score is:  0.27182324089138277
For  16  clusters, the average silhouette score is:  0.26291458847781496
For  17  clusters, the average silhouette score is:  0.27751208546019596
For  18  clusters, the average silhouette score is:  0.28200117540840053
For  19  clusters, the average silhouette score is:  0.27784706240404766
For  20  clusters, the average silhouette score is:  0.27919706380682835
For  21  clusters, the average silhouette score is:  0.27220684223398744
For  22  clusters, the average silhouette score is:  0.26122207375405015
For  23  clusters, the average silhouette score is:  0.

For  21  clusters, the average silhouette score is:  0.28353891893268707
For  22  clusters, the average silhouette score is:  0.26987764500117567
For  23  clusters, the average silhouette score is:  0.26371325807677704
For  24  clusters, the average silhouette score is:  0.26829474925082625
For  25  clusters, the average silhouette score is:  0.2697862503035406
For  26  clusters, the average silhouette score is:  0.2684914413710328
For  27  clusters, the average silhouette score is:  0.2705399956380139
For  28  clusters, the average silhouette score is:  0.2695174834025304
For  29  clusters, the average silhouette score is:  0.2658460296604881
For  30  clusters, the average silhouette score is:  0.2702433482042699
For  31  clusters, the average silhouette score is:  0.2602053669513056
For  32  clusters, the average silhouette score is:  0.2408327019158912
For  33  clusters, the average silhouette score is:  0.2580983855415897
For  34  clusters, the average silhouette score is:  0.26238

For  33  clusters, the average silhouette score is:  0.25964131986776245
For  34  clusters, the average silhouette score is:  0.25685920775361265
For  35  clusters, the average silhouette score is:  0.2585456459234893
For  36  clusters, the average silhouette score is:  0.248848324218379
For  37  clusters, the average silhouette score is:  0.2637844374622867
For  38  clusters, the average silhouette score is:  0.24333026393018753
For  39  clusters, the average silhouette score is:  0.2405119866121349
For  40  clusters, the average silhouette score is:  0.23434711146831155
For  41  clusters, the average silhouette score is:  0.2348126980394888
For  42  clusters, the average silhouette score is:  0.24951921023315488
For  43  clusters, the average silhouette score is:  0.24192570998335958
For  44  clusters, the average silhouette score is:  0.23144289802266302
For  45  clusters, the average silhouette score is:  0.20646796965876357
For  46  clusters, the average silhouette score is:  0.24

For  45  clusters, the average silhouette score is:  0.24081210199711184
For  46  clusters, the average silhouette score is:  0.2425955534321841
For  47  clusters, the average silhouette score is:  0.24322097186552794
For  48  clusters, the average silhouette score is:  0.24369903405380808
For  49  clusters, the average silhouette score is:  0.24392960912949155
For  50  clusters, the average silhouette score is:  0.24357267293520904
The best K is: 4.0
For iteration[ 17 ] The hamming loss is: 4.0  is 0.22233032198285846
For iteration[ 17 ] The hamming dist is: 4.0  is 0.6669909659485754
For  2  clusters, the average silhouette score is:  0.3412583721362144
For  3  clusters, the average silhouette score is:  0.36357542165726875
For  4  clusters, the average silhouette score is:  0.3755622306944317
For  5  clusters, the average silhouette score is:  0.36784571456430015
For  6  clusters, the average silhouette score is:  0.264968956504193
For  7  clusters, the average silhouette score is: 

For  5  clusters, the average silhouette score is:  0.36784571456430015
For  6  clusters, the average silhouette score is:  0.264968956504193
For  7  clusters, the average silhouette score is:  0.26759752382604046
For  8  clusters, the average silhouette score is:  0.27111141316513976
For  9  clusters, the average silhouette score is:  0.2666239754061406
For  10  clusters, the average silhouette score is:  0.27539290830614543
For  11  clusters, the average silhouette score is:  0.27205640490655647
For  12  clusters, the average silhouette score is:  0.2757821663842867
For  13  clusters, the average silhouette score is:  0.2764661499667152
For  14  clusters, the average silhouette score is:  0.28518785144395803
For  15  clusters, the average silhouette score is:  0.27330031499308327
For  16  clusters, the average silhouette score is:  0.28959291631006806
For  17  clusters, the average silhouette score is:  0.28356792268247194
For  18  clusters, the average silhouette score is:  0.274477

For  17  clusters, the average silhouette score is:  0.26272583411980555
For  18  clusters, the average silhouette score is:  0.2673512375616859
For  19  clusters, the average silhouette score is:  0.2708759592248567
For  20  clusters, the average silhouette score is:  0.2753382502247094
For  21  clusters, the average silhouette score is:  0.25739913817457416
For  22  clusters, the average silhouette score is:  0.29048010026312115
For  23  clusters, the average silhouette score is:  0.2674320141773634
For  24  clusters, the average silhouette score is:  0.26783969450664796
For  25  clusters, the average silhouette score is:  0.26326709783300206
For  26  clusters, the average silhouette score is:  0.26550958620145576
For  27  clusters, the average silhouette score is:  0.2702302115394295
For  28  clusters, the average silhouette score is:  0.2702177099902227
For  29  clusters, the average silhouette score is:  0.266255568925368
For  30  clusters, the average silhouette score is:  0.2684

For  28  clusters, the average silhouette score is:  0.2759812167558686
For  29  clusters, the average silhouette score is:  0.2785001239899688
For  30  clusters, the average silhouette score is:  0.27588332190700204
For  31  clusters, the average silhouette score is:  0.2686437583836477
For  32  clusters, the average silhouette score is:  0.26093641936120543
For  33  clusters, the average silhouette score is:  0.24533553717537732
For  34  clusters, the average silhouette score is:  0.26037265420321715
For  35  clusters, the average silhouette score is:  0.24334343822490154
For  36  clusters, the average silhouette score is:  0.23820881336294475
For  37  clusters, the average silhouette score is:  0.23660148172403686
For  38  clusters, the average silhouette score is:  0.23139455252874272
For  39  clusters, the average silhouette score is:  0.230718027866308
For  40  clusters, the average silhouette score is:  0.22603710514396244
For  41  clusters, the average silhouette score is:  0.2

For  40  clusters, the average silhouette score is:  0.24491179343762987
For  41  clusters, the average silhouette score is:  0.24176095065045436
For  42  clusters, the average silhouette score is:  0.22393557399347092
For  43  clusters, the average silhouette score is:  0.2246351281901214
For  44  clusters, the average silhouette score is:  0.2236475330375949
For  45  clusters, the average silhouette score is:  0.22167069879828036
For  46  clusters, the average silhouette score is:  0.23039275731903688
For  47  clusters, the average silhouette score is:  0.2258273548858598
For  48  clusters, the average silhouette score is:  0.22638910191885586
For  49  clusters, the average silhouette score is:  0.22570602511914
For  50  clusters, the average silhouette score is:  0.22230490628485783
The best K is: 4.0
For iteration[ 26 ] The hamming loss is: 4.0  is 0.22233032198285846
For iteration[ 26 ] The hamming dist is: 4.0  is 0.6669909659485754
For  2  clusters, the average silhouette score 

For  2  clusters, the average silhouette score is:  0.3412583721362144
For  3  clusters, the average silhouette score is:  0.36357542165726875
For  4  clusters, the average silhouette score is:  0.3755622306944317
For  5  clusters, the average silhouette score is:  0.36651763171784835
For  6  clusters, the average silhouette score is:  0.264968956504193
For  7  clusters, the average silhouette score is:  0.2616343044993276
For  8  clusters, the average silhouette score is:  0.27085025820742464
For  9  clusters, the average silhouette score is:  0.25207514295294825
For  10  clusters, the average silhouette score is:  0.27599866613732993
For  11  clusters, the average silhouette score is:  0.25999809020344733
For  12  clusters, the average silhouette score is:  0.25933677306456826
For  13  clusters, the average silhouette score is:  0.26017536717243045
For  14  clusters, the average silhouette score is:  0.26171811454055915
For  15  clusters, the average silhouette score is:  0.272098118

For  14  clusters, the average silhouette score is:  0.28369948699980607
For  15  clusters, the average silhouette score is:  0.2708485499679269
For  16  clusters, the average silhouette score is:  0.2748210185588242
For  17  clusters, the average silhouette score is:  0.26919767759898666
For  18  clusters, the average silhouette score is:  0.2744167535064922
For  19  clusters, the average silhouette score is:  0.2739474188173107
For  20  clusters, the average silhouette score is:  0.2730774692677384
For  21  clusters, the average silhouette score is:  0.27180506112819924
For  22  clusters, the average silhouette score is:  0.2851526901729867
For  23  clusters, the average silhouette score is:  0.28044785560653857
For  24  clusters, the average silhouette score is:  0.2819860391769617
For  25  clusters, the average silhouette score is:  0.27588421775811794
For  26  clusters, the average silhouette score is:  0.2752748157459476
For  27  clusters, the average silhouette score is:  0.2597

For  26  clusters, the average silhouette score is:  0.24734589761132747
For  27  clusters, the average silhouette score is:  0.2470575671569502
For  28  clusters, the average silhouette score is:  0.2588783044389803
For  29  clusters, the average silhouette score is:  0.2710815332632556
For  30  clusters, the average silhouette score is:  0.2597707566743536
For  31  clusters, the average silhouette score is:  0.26559648163570676
For  32  clusters, the average silhouette score is:  0.25874667223996684
For  33  clusters, the average silhouette score is:  0.2629820528378473
For  34  clusters, the average silhouette score is:  0.2699231848152154
For  35  clusters, the average silhouette score is:  0.2717517746234672
For  36  clusters, the average silhouette score is:  0.27047128495722167
For  37  clusters, the average silhouette score is:  0.25147147107875445
For  38  clusters, the average silhouette score is:  0.25660061576872106
For  39  clusters, the average silhouette score is:  0.265

For  38  clusters, the average silhouette score is:  0.26414631199899846
For  39  clusters, the average silhouette score is:  0.25340244276362267
For  40  clusters, the average silhouette score is:  0.24800352806495923
For  41  clusters, the average silhouette score is:  0.24368380167595033
For  42  clusters, the average silhouette score is:  0.23603353618215533
For  43  clusters, the average silhouette score is:  0.23667369253001255
For  44  clusters, the average silhouette score is:  0.23952635774370923
For  45  clusters, the average silhouette score is:  0.24211007290236033
For  46  clusters, the average silhouette score is:  0.24213187480543663
For  47  clusters, the average silhouette score is:  0.22917933546693828
For  48  clusters, the average silhouette score is:  0.2430146315448542
For  49  clusters, the average silhouette score is:  0.22452071860721137
For  50  clusters, the average silhouette score is:  0.24215692104718028
The best K is: 4.0
For iteration[ 35 ] The hamming l

For  49  clusters, the average silhouette score is:  0.21248507023665944
For  50  clusters, the average silhouette score is:  0.2129966303549015
The best K is: 4.0
For iteration[ 37 ] The hamming loss is: 4.0  is 0.22233032198285846
For iteration[ 37 ] The hamming dist is: 4.0  is 0.6669909659485754
For  2  clusters, the average silhouette score is:  0.3412583721362144
For  3  clusters, the average silhouette score is:  0.36357542165726875
For  4  clusters, the average silhouette score is:  0.37567709025469104
For  5  clusters, the average silhouette score is:  0.3684660773649927
For  6  clusters, the average silhouette score is:  0.264968956504193
For  7  clusters, the average silhouette score is:  0.26164222305771795
For  8  clusters, the average silhouette score is:  0.2572065217909239
For  9  clusters, the average silhouette score is:  0.26467327145889
For  10  clusters, the average silhouette score is:  0.26584456386794425
For  11  clusters, the average silhouette score is:  0.265

For  9  clusters, the average silhouette score is:  0.2667443861775196
For  10  clusters, the average silhouette score is:  0.2661791924101105
For  11  clusters, the average silhouette score is:  0.2739298289950333
For  12  clusters, the average silhouette score is:  0.2734797068576878
For  13  clusters, the average silhouette score is:  0.2801688604849336
For  14  clusters, the average silhouette score is:  0.26668125656697755
For  15  clusters, the average silhouette score is:  0.25907022034871197
For  16  clusters, the average silhouette score is:  0.27643576003546144
For  17  clusters, the average silhouette score is:  0.2767528117719131
For  18  clusters, the average silhouette score is:  0.26655666828580904
For  19  clusters, the average silhouette score is:  0.2725448228398043
For  20  clusters, the average silhouette score is:  0.2680900983413033
For  21  clusters, the average silhouette score is:  0.2712770452098621
For  22  clusters, the average silhouette score is:  0.267442

For  21  clusters, the average silhouette score is:  0.2726426936396976
For  22  clusters, the average silhouette score is:  0.2728031313078728
For  23  clusters, the average silhouette score is:  0.26954553951604776
For  24  clusters, the average silhouette score is:  0.26707554074082634
For  25  clusters, the average silhouette score is:  0.2680476798364046
For  26  clusters, the average silhouette score is:  0.2638191155910904
For  27  clusters, the average silhouette score is:  0.2561778285038968
For  28  clusters, the average silhouette score is:  0.26163944892695584
For  29  clusters, the average silhouette score is:  0.26445808191843023
For  30  clusters, the average silhouette score is:  0.25742031361330564
For  31  clusters, the average silhouette score is:  0.2669469130812867
For  32  clusters, the average silhouette score is:  0.2662284992338063
For  33  clusters, the average silhouette score is:  0.2680013420421416
For  34  clusters, the average silhouette score is:  0.2655

For  33  clusters, the average silhouette score is:  0.24049496099651624
For  34  clusters, the average silhouette score is:  0.22569269114215756
For  35  clusters, the average silhouette score is:  0.22925442848121605
For  36  clusters, the average silhouette score is:  0.24648142878492457
For  37  clusters, the average silhouette score is:  0.2298242524893586
For  38  clusters, the average silhouette score is:  0.2481283024258994
For  39  clusters, the average silhouette score is:  0.25215143489408015
For  40  clusters, the average silhouette score is:  0.24570951435678157
For  41  clusters, the average silhouette score is:  0.2456612782427671
For  42  clusters, the average silhouette score is:  0.246236260466821
For  43  clusters, the average silhouette score is:  0.23906462725342262
For  44  clusters, the average silhouette score is:  0.24713400507356004
For  45  clusters, the average silhouette score is:  0.2438193049135251
For  46  clusters, the average silhouette score is:  0.24

For  45  clusters, the average silhouette score is:  0.22537248705093502
For  46  clusters, the average silhouette score is:  0.22503181421071558
For  47  clusters, the average silhouette score is:  0.23982913485474272
For  48  clusters, the average silhouette score is:  0.24131553159129637
For  49  clusters, the average silhouette score is:  0.23753340560349517
For  50  clusters, the average silhouette score is:  0.21827983479872318
The best K is: 4.0
For iteration[ 46 ] The hamming loss is: 4.0  is 0.22233032198285846
For iteration[ 46 ] The hamming dist is: 4.0  is 0.6669909659485754
For  2  clusters, the average silhouette score is:  0.3412583721362144
For  3  clusters, the average silhouette score is:  0.36357542165726875
For  4  clusters, the average silhouette score is:  0.3814920813318203
For  5  clusters, the average silhouette score is:  0.3684660773649927
For  6  clusters, the average silhouette score is:  0.264968956504193
For  7  clusters, the average silhouette score is: 

For  5  clusters, the average silhouette score is:  0.3684094524543376
For  6  clusters, the average silhouette score is:  0.264968956504193
For  7  clusters, the average silhouette score is:  0.2613870455574065
For  8  clusters, the average silhouette score is:  0.25623881670079307
For  9  clusters, the average silhouette score is:  0.2782041264577876
For  10  clusters, the average silhouette score is:  0.26619745798702327
For  11  clusters, the average silhouette score is:  0.2748109366916229
For  12  clusters, the average silhouette score is:  0.27337024177954256
For  13  clusters, the average silhouette score is:  0.2606651962758296
For  14  clusters, the average silhouette score is:  0.28335072749396933
For  15  clusters, the average silhouette score is:  0.27148778900843656
For  16  clusters, the average silhouette score is:  0.27764788526653356
For  17  clusters, the average silhouette score is:  0.26941560113866925
For  18  clusters, the average silhouette score is:  0.26685831

In [63]:
print("Average Hamming Loss: ", np.mean(all_hamming))
print("Std Hamming Loss:", np.std(all_hamming))

print("Average Hamming distance: ", np.mean(all_dist))
print("Std Hamming distance: ", np.std(all_dist))

print("Average of Hamming score: ",(1 - np.mean(all_hamming)))
print("Std Hamming score:  ",np.std(all_hamming))

 Average Hamming Loss:  0.22233032198285843
 Std Hamming Loss: 2.7755575615628914e-17
 Average Hamming distance:  0.6669909659485755
 Std Hamming distance:  1.1102230246251565e-16
 Average of Hamming score:  0.7776696780171416
 Std Hamming score:   2.7755575615628914e-17


### 3. ISLR 12.6.2

see jpg document at notebook file

### References

https://numpy.org/doc/stable/reference/generated/numpy.vstack.html


https://www.tensorflow.org/addons/api_docs/python/tfa/metrics/HammingLoss#:~:text=Hamming%20loss%20is%20the%20fraction,penalizes%20only%20the%20individual%20labels.

https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html

https://scikit-learn.org/stable/modules/generated/sklearn.multiclass.OneVsRestClassifier.html

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.silhouette_samples.html
